server/explorer/views.py
from flask import Blueprint, render_template
from ..services import TransactionService
from webargs.flaskparser import use_args
from ..services import BalanceService
from ..services import AddressService
from ..services import TokenService
from ..services import BlockService
from flask import redirect, url_for
from webargs import fields
from pony import orm
from .. import utils
import math

from datetime import timedelta
from ..models import Index, Transfer, Transaction, Balance, Peer
from ..models import ChartTransactions, ChartVolume

blueprint = Blueprint("explorer", __name__)


@blueprint.route("/")
@orm.db_session
def overview():
    latest = BlockService.latest_block()
    supply_data = utils.supply(latest.height)
    supply = utils.amount(supply_data["supply"])

    transactions = TransactionService.transactions_frontend(pagesize=10)
    # transactions = []

    start = latest.created - timedelta(hours=24)

    diff = utils.make_request("getmininginfo")

    pow_diff = 0
    pos_diff = 0

    if not diff["error"]:
        pow_diff = diff["result"]["difficulty"]["proof-of-work"]
        pos_diff = diff["result"]["difficulty"]["proof-of-stake"]

    stats = {
        "volume": round(
            orm.select(
                t.amount for t in Transaction if t.created > start
            ).sum(),
            2,
        ),
        "count": {
            "transactions": Transaction.select(
                lambda t: t.created > start
            ).count(distinct=False),
            "addresses": Balance.select(lambda b: b.amount > 0).count(
                distinct=False
            ),
        },
        "supply": supply,
        "diff": {
            "pow": round(pow_diff, 6),
            "pos": round(pos_diff, 4),
        },
    }

    blocks = BlockService.blocks(pagesize=10)

    return render_template(
        "pages/overview.html",
        latest=latest,
        blocks=blocks,
        transactions=transactions,
        stats=stats,
    )


@blueprint.route("/list/blocks/", defaults={"page": 1})
@blueprint.route("/list/blocks/<int:page>")
@orm.db_session
def blocks(page):
    size = 30
    latest = BlockService.latest_block()
    total = math.ceil(latest.height / size)

    blocks = BlockService.blocks(page, size)
    pagination = utils.pagination("explorer.blocks", page, size, total)

    return render_template(
        "pages/blocks.html", pagination=pagination, blocks=blocks
    )


@blueprint.route("/get/block/<string:blockhash>", defaults={"page": 1})
@blueprint.route("/get/block/<string:blockhash>/<int:page>")
@orm.db_session
def block(blockhash, page):
    size = 10

    if block := BlockService.get_by_hash(blockhash):
        transactions = block.txs.page(page, pagesize=size)

        total = math.ceil(block.tx_count / size)
        pagination = utils.pagination("explorer.block", page, size, total)

        title = f"Block #{block.height}"

        return render_template(
            "pages/block.html",
            block=block,
            transactions=transactions,
            pagination=pagination,
            title=title,
        )

    return render_template("pages/404.html")


@blueprint.route("/list/transactions", defaults={"page": 1})
@blueprint.route("/list/transactions/<int:page>")
@orm.db_session
def transactions(page):
    size = 100

    transactions_data = TransactionService.transactions(page, size)
    transactions = []

    for entry in transactions_data:
        transaction = entry[0]
        amount = entry[1]

        transactions.append(
            {
                "height": transaction.height,
                "blockhash": (
                    transaction.block.blockhash if transaction.block else None
                ),
                "timestamp": transaction.created.timestamp(),
                "created": transaction.created,
                "block": transaction.block,
                "txid": transaction.txid,
                "amount": amount,
            }
        )

    count = TransactionService.count()
    total = math.ceil(count / size)

    pagination = utils.pagination("explorer.transactions", page, size, total)

    return render_template(
        "pages/transactions.html",
        pagination=pagination,
        transactions=transactions,
    )


@blueprint.route("/get/transaction/<string:txid>")
@orm.db_session
def transaction(txid):
    title = f"Transaction {txid[:16]}..."
    transaction = TransactionService.get_by_txid(txid)

    if transaction:
        return render_template(
            "pages/transaction.html", transaction=transaction, title=title
        )

    return render_template("pages/404.html")


@blueprint.route("/get/address/<string:address>", defaults={"page": 1})
@blueprint.route("/get/address/<string:address>/<int:page>")
@orm.db_session
def address(address, page):
    size = 10

    if address := AddressService.get_by_address(address):
        index = address.index.order_by(orm.desc(Index.created)).page(
            page, pagesize=size
        )
        transactions = []

        for entry in index:
            transactions.append(entry.transaction)

        total = math.ceil(address.txcount / size)
        pagination = utils.pagination("explorer.address", page, size, total)

        title = f"Address {address.address}"

        return render_template(
            "pages/address.html",
            address=address,
            transactions=transactions,
            pagination=pagination,
            title=title,
        )

    return render_template("pages/404.html")


@blueprint.route("/list/tokens", defaults={"page": 1})
@blueprint.route("/list/tokens/<int:page>")
@orm.db_session
def tokens(page):
    size = 100

    tokens = TokenService.list(page, size)
    count = TokenService.count()
    total = math.ceil(count / size)

    pagination = utils.pagination("explorer.tokens", page, size, total)

    return render_template(
        "pages/tokens.html", pagination=pagination, tokens=tokens
    )


@blueprint.route("/list/holders", defaults={"page": 1})
@blueprint.route("/list/holders/<int:page>")
@orm.db_session
def holders(page):
    size = 100

    balances = BalanceService.holders(page, size)
    count = BalanceService.holders_count()
    total = math.ceil(count / size)

    pagination = utils.pagination("explorer.holders", page, size, total)

    return render_template(
        "pages/holders.html",
        pagination=pagination,
        balances=balances,
        current_page=page,
        page_size=size,
    )


@blueprint.route("/get/map")
@orm.db_session
def peers_map():
    peers = Peer.select()
    return render_template("pages/map.html", peers=peers)


@blueprint.route("/get/token/<string:address>", defaults={"page": 1})
@blueprint.route("/get/token/<string:address>/<int:page>")
@orm.db_session
def token(address, page):
    if token := TokenService.get_by_address(address):
        title = f"Token {token.ticker}"

        size = 100
        total = math.ceil(token.txcount / size)

        transactions = orm.select(
            t.transaction for t in Transfer if t.token == token
        ).page(page, size)

        pagination = utils.pagination("explorer.token", page, size, total)

        return render_template(
            "pages/token.html",
            pagination=pagination,
            transactions=transactions,
            # transfers=transfers,
            token=token,
            title=title,
        )

    return render_template("pages/404.html")


@blueprint.route("/search")
@use_args({"query": fields.Str(required=True)}, location="query")
@orm.db_session
def search(args):
    if args["query"].isdigit():
        if block := BlockService.get_by_height(args["query"]):
            return redirect(
                url_for(
                    "explorer.block", blockhash=block.blockhash, _external=True
                )
            )

    else:
        if len(args["query"]) == 64:
            if block := BlockService.get_by_hash(args["query"]):
                return redirect(
                    url_for(
                        "explorer.block",
                        blockhash=block.blockhash,
                        _external=True,
                    )
                )

            return redirect(
                url_for(
                    "explorer.transaction", txid=args["query"], _external=True
                )
            )

        elif len(args["query"]) == 40:
            return redirect(
                url_for("explorer.token", address=args["query"], _external=True)
            )

        elif len(args["query"]) == 34:
            return redirect(
                url_for(
                    "explorer.address", address=args["query"], _external=True
                )
            )

    return redirect(url_for("explorer.overview", _external=True))


@blueprint.route("/tx/<string:txid>")
def tx_redirect(txid):
    return redirect(url_for("explorer.transaction", txid=txid, _external=True))


@blueprint.route("/data/chart")
@orm.db_session
def chart():
    chart_transactions = (
        ChartTransactions.select()
        .order_by(orm.desc(ChartTransactions.time))
        .limit(30)
    )

    chart_volume = (
        ChartVolume.select().order_by(orm.desc(ChartVolume.time)).limit(30)
    )

    chart_data = {
        "transactions": {
            "labels": [
                tx.time.strftime("%d-%m-%Y") for tx in chart_transactions
            ],
            "data": [tx.value for tx in chart_transactions],
        },
        "volume": {
            "labels": [
                volume.time.strftime("%d-%m-%Y") for volume in chart_volume
            ],
            "data": [volume.value for volume in chart_volume],
        },
    }

    return utils.response(chart_data)


@blueprint.route("/data/peers")
@orm.db_session
def peers():
    peers = []

    for peer in Peer.select():
        peers.append(
            {
                "last": peer.last,
                "address": peer.address,

server/templates/pages/address.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="h3 text-gray-800">Address</h1>

				<div id="address-info-table">
					<div class="table-responsive">
						<table class="table table-striped table-hover">
							<tbody>
								<tr>
									<td>Address</td>
									<td>
										<span class="font-monospace">
											{{ address.address }}
										</span>
									</td>
								</tr>
								<tr>
									<td>Balance</td>
									<td>
										<span>{{ address.balance.amount|amount }}</span> EQPAY
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>

				<div class="card mb-3">
					<div class="card-body">
						{% for balance in address.token_balances %}
							{{ balance.amount|amount }} {{ balance.token.ticker }}
						{% endfor %}
					</div>
				</div>

				{% for transaction in transactions %}
					<div class="card mb-3 fz-14">
						<div class="card-header">
							<a href="{{ url_for('explorer.transaction', txid=transaction.txid) }}" class="font-monospace">
								{{ transaction.txid }}
							</a>
							<span class="float-md-end d-sm-block">
								<span class="local-time" time="{{ transaction.created|timestamp }}"></span>
							</span>
						</div>
						<div class="card-body">
							{% include "elements/details.html" %}
						</div>
					</div>
				{% endfor %}
			</div>
		</div>

		{% if pagination %}
			<div class="pagination">
				{% if pagination.pages|length > 1 %}
					{% if pagination.previous %}
						<a href="{{ url_for(pagination.url, page=pagination.previous, address=address.address) }}" class="button">
							<i class="fas fa-fw fa-chevron-left"></i>
						</a>
					{% endif %}

					{% for page in pagination.pages %}
						<a href="{{ url_for(pagination.url, page=page, address=address.address) }}" class="button {% if page == pagination.current %}not-active{% endif %}">
							{{ page }}
						</a>
					{% endfor %}

					{% if pagination.next %}
						<a href="{{ url_for(pagination.url, page=pagination.next, address=address.address) }}" class="button">
							<i class="fas fa-fw fa-chevron-right"></i>
						</a>
					{% endif %}
				{% endif %}
			</div>
		{% endif %}
	</div>
{% endblock content %}

server/templates/pages/block.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="h3 text-gray-800">Block</h1>

				<div id="block-info-table">
					<div class="mb-3">
						<div class="table-responsive">
							<table class="table table-striped table-hover">
								<tbody>
									<tr>
										<td>Height</td>
										<td id="block-info-height" data-block-info-height="{{ block.height }}">{{ block.height }} (<b>Confirmations {{ block.confirmations }}</b>)</td>
									</tr>
									<tr>
										<td>Timestamp</td>
										<td>
											<span class="local-time" time="{{ block.created|timestamp }}"></span> (<b>{{ block.timestamp }}</b>)
										</td>
									</tr>
									<tr>
										<td>Block Hash</td>
										<td id="block-info-hash" data-block-info-hash="{{ block.blockhash }}" class="font-monospace">{{ block.blockhash }}</td>
									</tr>
									<tr>
										<td>Previous Block</td>

										{% if block.previous_block %}
											<td>
												<a href="{{ url_for('explorer.block', blockhash=block.previous_block.blockhash) }}" class="font-monospace">
													{{ block.previous_block.blockhash }}
												</a>
											</td>
										{% else%}
											<td>
												<b>Genesis block</b>
											</td>
										{% endif %}
									</tr>
									<tr>
										<td>Next Block</td>

										{% if block.next_block %}
											<td>
												<a href="{{ url_for('explorer.block', blockhash=block.next_block.blockhash) }}" class="font-monospace">
													{{ block.next_block.blockhash }}
												</a>
											</td>
										{% else%}
											<td>
												<b>This is latest block</b>
											</td>
										{% endif %}
									</tr>
									<tr>
										<td>Merkle Root</td>
										<td>
											<span class="font-monospace">
												{{ block.merkleroot }}
											</span>
										</td>
									</tr>
									<tr>
										<td>Size</td>
										<td>{{ block.size }} Bytes</td>
									</tr>
									<tr>
										<td>Version</td>
										<td>{{ block.version }}</td>
									</tr>
									<tr>
										<td>Transactions</td>
										<td>{{ block.tx_count }}</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>

				{% include "elements/transactions.html" %}

				{% if pagination %}
					{% if pagination.pages|length > 1 %}
						{% if pagination.previous %}
							<a href="{{ url_for(pagination.url, page=pagination.previous, blockhash=block.blockhash) }}" class="button">
								<i class="fas fa-fw fa-chevron-left"></i>
							</a>
						{% endif %}

						{% for page in pagination.pages %}
							<a href="{{ url_for(pagination.url, page=page, blockhash=block.blockhash) }}" class="button {% if page == pagination.current %}active{% endif %} {% if page == pagination.current - 1 or page == pagination.current + 1 %}show-xs{% endif %}">
								{{ page }}
							</a>
						{% endfor %}

						{% if pagination.next %}
							<a href="{{ url_for(pagination.url, page=pagination.next, blockhash=block.blockhash) }}" class="button">
								<i class="fas fa-fw fa-chevron-right"></i>
							</a>
						{% endif %}
					{% endif %}
				{% endif %}
			</div>
		</div>
	</div>
{% endblock content %}

server/templates/pages/blocks.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="h4">Blocks</h1>

				<div class="table-responsive">
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th scope="col">Height</th>
								<th scope="col">Hash</th>
								<th scope="col">Time</th>
								<th scope="col">Txs</th>
								<th scope="col">Reward</th>
							</tr>
						</thead>
						<tbody>
							{% for block in blocks %}
								<tr data-height="{{ block.height }}">
									<td>
										{{ block.height }}
									</td>
									<td>
										<a href="{{ url_for('explorer.block', blockhash=block.blockhash) }}" class="font-monospace">
											{{ block.blockhash }}
										</a>
									</td>
									<td>
										<span class="local-time" time="{{ block.created|timestamp }}"/>
									</td>
									<td class="non-mobile">
										{{ block.tx_count }}
									</td>
									<td>
										{{ block.reward|amount }} EQPAY
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>

		{% include "elements/pagination.html" %}
	</div>
{% endblock content %}

server/templates/pages/holders.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="h4">Holders</h1>

				<div class="table-responsive">
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th scope="col"></th>
								<th scope="col">Address</th>
								<th scope="col">Balance</th>
							</tr>
						</thead>
						<tbody>
							{% for balance in balances %}
								<tr>
									<td>{{ loop.index + (current_page - 1) * page_size}}</td>
									<td>
										<a href="{{ url_for('explorer.address', address=balance.address.address) }}" class="font-monospace">
											{{ balance.address.address }}
										</a>
									</td>
									<td>
										<span>{{ balance.amount|amount }}</span> EQPAY
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>

		{% include "elements/pagination.html" %}
	</div>
{% endblock content %}

server/templates/pages/map.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="mb-3">
					Network map
				</h1>

				<div id="map"></div>

				<div class="table-responsive mt-3">
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th scope="col">Address</th>
								<th scope="col">Version</th>
								<th scope="col">Country</th>
								<th scope="col">Last seen</th>
							</tr>
						</thead>
						<tbody>
							{% for peer in peers %}
								<tr>
									<td>
										{{ peer.address }}:{{ peer.port }}
									</td>
									<td>
										{{ peer.subver }}
									</td>
									<td>
										{{ peer.country }} <img style="max-width: 32px;" src="https://countryflagsapi.com/png/{{ peer.code }}">
									</td>
									<td>
										<span class="local-time" time="{{ peer.last|timestamp }}"></span>
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

	<script type="text/javascript">
		$.get("{{ url_for('explorer.peers') }}", function(data) {
			let map = L.map("map").setView([40, 0], 2.5);

			L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
				attribution: "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors"
			}).addTo(map);

			const peers = data["result"]

			let taken_locations = []

			for (let index in peers) {
				let dist = Math.random() * 0.1
				let angle = Math.random() * Math.PI * 2

				let lat = peers[index]["lat"] + (dist * Math.cos(angle))
				let lon = peers[index]["lon"] + (dist * Math.sin(angle))

				const description = peers[index]["address"] + ":" + peers[index]["port"] + " " + peers[index]["subver"]

				L.marker([lat, lon]).addTo(map)
					.bindPopup(description);
			}
		})
	</script>
{% endblock content %}

server/templates/pages/overview.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-body">
						<div class="stats">
							<div class="stats-item">
								<div>
									<span>
										<i class="fab fa-fw fa-buffer"></i>
									</span>
								</div>
								<div>Block Height</div>
								{{ latest.height }}
							</div>
							<div class="stats-item">
								<div>
									<span>
										<i class="far fa-fw fa-clock"></i>
									</span>
								</div>
								<div>Latest Block Time</div>
								<div class="local-time-hour" time="{{ latest.created|timestamp }}"></div>
							</div>
							<div class="stats-item">
								<div>
									<span>
										<i class="fas fa-fw fa-sync"></i>
									</span>
								</div>
								<div>Volume (24h)</div>
								{{ stats.volume|amount }} EQPAY
							</div>
							<div class="stats-item">
								<div>
									<span>
										<i class="fas fa-fw fa-exchange-alt"></i>
									</span>
								</div>
								<div>Transactions (24h)</div>
								{{ stats.count.transactions }}
							</div>
							<div class="stats-item">
								<div>
									<span>
										<i class="fas fa-fw fa-wallet"></i>
									</span>
								</div>
								<div>Total Addresses</div>
								{{ stats.count.addresses }}
							</div>
							<div class="stats-item">
								<div>
									<span>
										<i class="fas fa-fw fa-coins"></i>
									</span>
								</div>
								<div>Supply</div>
								{{ stats.supply|amount }} EQPAY
							</div>

							<div class="stats-item">
								<div>
									<span>
										<i class="fas fa-fw fa-vector-square"></i>
									</span>
								</div>
								<div>Difficulty PoW</div>
								{{ stats.diff.pow }}
							</div>
							<div class="stats-item">
								<div>
									<span>
										<i class="fas fa-fw fa-stop"></i>
									</span>
								</div>
								<div>Difficulty PoS</div>
								{{ stats.diff.pos }}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-6 col-md-12">
				<canvas id="volume-chart"></canvas>
			</div>
			<div class="col-lg-6 col-md-12">
				<canvas id="transactions-chart"></canvas>
			</div>
		</div>

		<script type="text/javascript">
			const ctx_volume = document.getElementById("volume-chart").getContext("2d");
			const ctx_transactions = document.getElementById("transactions-chart").getContext("2d");
			$.ajax({
				type: "GET",
				url: "{{ url_for("explorer.chart") }}",
				success: function(data) {
					const volume = new Chart(ctx_volume, {
						type: "bar",
						data: {
							labels: data.result.volume.labels.reverse(),
							datasets: [{
								label: " EQPAY volume",
								data: data.result.volume.data.reverse(),
								borderWidth: 1,
								backgroundColor: "rgb(32,89,154)",
								borderColor: "rgb(32,89,154)",
								minBarLength: 5
							}]
						},
						options: {
							scales: {
								y: {
									beginAtZero: true
								}
							}
						}
					})

					const transactions = new Chart(ctx_transactions, {
						type: "line",
						data: {
							labels: data.result.transactions.labels.reverse(),
							datasets: [{
								label: " Transaction",
								data: data.result.transactions.data.reverse(),
								backgroundColor: "rgb(32,89,154)",
								borderColor: "rgb(32,89,154)",
							}]
						},
						options: {
							scales: {
								y: {
									beginAtZero: true
								}
							}
						}
					})
				}
			})
		</script>

		<div class="row">
			<div class="col-lg-6 col-md-12">
				<h4 class="mt-3">Latest blocks</h4>
				<div class="card">
					<ul class="list-group list-group-flush">
						{% for block in blocks %}
							<li class="list-group-item">
								<div style="display: flex;align-content: center;">
									<div style="margin: auto;">
										<i style="color: #000000;" class="fab fa-fw fa-buffer"></i>
										<a class="font-monospace" href="{{ url_for('explorer.block', blockhash=block.blockhash) }}">
											{{ block.height }}
										</a>
									</div>
									<div style="margin: auto;">
										<div>Created: <span class="local-time" time="{{ block.created|timestamp }}"/></div>
										<div>Transactions: {{ block.tx_count }}</div>
									</div>
									<div style="margin: auto;">
										Reward: {{ block.reward|amount }} EQPAY
									</div>
								</div>
							</li>
						{% endfor %}
					</ul>
				</div>
			</div>

			<div class="col-lg-6 col-md-12">
				<h4 class="mt-3">Latest transactions</h4>
				<div class="card">
					<ul class="list-group list-group-flush">
						{% for transaction in transactions %}
							<li class="list-group-item">
								<div style="display: flex;">
									<div style="display: flex;">
										<i style="margin: auto 10px auto 0px; color: #000000;" class="fas fa-fw fa-exchange-alt"></i>
									</div>
									<div style="overflow: hidden;">
										<div style="white-space: nowrap;max-width: 500px;">
											<a class="font-monospace" style="overflow: hidden;text-overflow: ellipsis;display: block;" href="{{ url_for('explorer.transaction', txid=transaction.txid) }}">{{ transaction.txid }}</a>
										</div>
										<span>Amount: {{ transaction.amount|amount }} EQPAY</span>
									</div>
								</div>
							</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

server/templates/pages/token.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="h4">Token</h1>

				<div id="tx-info-table">
					<div class="mb-3">
						<div class="table-responsive">
							<table class="table table-striped table-hover">
								<tbody>
									<tr>
										<td>Name</td>
										<td>{{ token.name }}</td>
									</tr>
									<tr>
										<td>Address</td>
										<td class="font-monospace">{{ token.address }}</td>
									</tr>
									<tr>
										<td>Transaction</td>
										<td>
											<a href="{{ url_for('explorer.transaction', txid=token.transaction.txid) }}" class="font-monospace">{{ token.transaction.txid }}</a>
										</td>
									</tr>
									<tr>
										<td>Issuer</td>
										<td>
											<a href="{{ url_for('explorer.address', address=token.issuer.address) }}" class="font-monospace">{{ token.issuer.address }}</a>
										</td>
									</tr>

									<tr>
										<td>Supply</td>
										<td>
											<span>{{ token.supply|amount }}</span> {{ token.ticker }}
										</td>
									</tr>
									<tr>
										<td>Ticker</td>
										<td>{{ token.ticker }}</td>
									</tr>
									<tr>
										<td>Decimals</td>
										<td>{{ token.decimals }}</td>
									</tr>
									<tr>
										<td>Holders</td>
										<td>{{ token.holders }}</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>

				{% include "elements/transactions.html" %}

				<div class="mb-3">
					{% if pagination %}
						{% if pagination.pages|length > 1 %}
							{% if pagination.previous %}
								<a href="{{ url_for(pagination.url, page=pagination.previous, address=token.address) }}" class="button">
									<i class="fas fa-fw fa-chevron-left"></i>
								</a>
							{% endif %}

							{% for page in pagination.pages %}
								<a href="{{ url_for(pagination.url, page=page, address=token.address) }}" class="button {% if page == pagination.current %}active{% endif %} {% if page == pagination.current - 1 or page == pagination.current + 1 %}show-xs{% endif %}">
									{{ page }}
								</a>
							{% endfor %}

							{% if pagination.next %}
								<a href="{{ url_for(pagination.url, page=pagination.next, address=token.address) }}" class="button">
									<i class="fas fa-fw fa-chevron-right"></i>
								</a>
							{% endif %}
						{% endif %}
					{% endif %}
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

server/templates/pages/tokens.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="h4">Tokens</h1>

				<div class="table-responsive">
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th scope="col">Name</th>
								<th scope="col">Ticker</th>
								<th scope="col">Contract address</th>
								<th scope="col">Created</th>
								<th scope="col">Supply</th>
								<th scope="col">Holders</th>
							</tr>
						</thead>
						<tbody>
							{% for token in tokens %}
								<tr>
									<td>
										{{ token.name }}
									</td>
									<td>
										{{ token.ticker }}
									</td>
									<td>
										<a href="{{ url_for('explorer.token', address=token.address) }}" class="font-monospace">
											{{ token.address }}
										</a>
									</td>
									<td>
										<span class="local-time" time="{{ token.created|timestamp }}"></span>
									</td>
									<td>
										{{ token.supply|amount }} {{ token.ticker }}
									</td>
									<td>
										{{ token.holders }}
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>

		{% include "elements/pagination.html" %}
	</div>
{% endblock content %}